name: Generate Translations

on:
  push:
    branches:
      - develop
    paths:
      - 'ui/src/translations/en.json'

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  generate-translations:
    name: Generate Translations and Create PR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2  # Ensures that at least two commits are fetched for comparison

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install gitpython openai

    - name: Create a new branch
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "actions@github.com"
        BRANCH_NAME="translations/update-translations-$(date +%s)"
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
        git checkout -b $BRANCH_NAME

    - name: Generate translations
      run: python ui/src/translations/generate_translations.py

    - name: Commit and push changes
      run: |
        git add ui/src/translations/*.json
        git commit -m "Auto-generate translations from en.json"
        git push --set-upstream origin ${{ env.BRANCH_NAME }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.BRANCH_NAME }}
        base: develop
        commit-message: "Auto-generate translations from en.json"
        title: "Auto-generate translations from en.json"
        body: "This PR was created automatically by a GitHub Action."
        labels: area/frontend
        assignees: anna-geller
        reviewers: anna-geller

    - name: Upload JSON files as artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: translation-json-files
        path: ui/src/translations/*.json